name: Create Release

on:
  workflow_dispatch:

jobs:
  create-release:
    uses: MCEngine-Action/gradle/.github/workflows/create-release-extension-with-jar.yml@master
    with:
      repo-name: ${{ github.repository }}
    secrets:
      USER_GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
